### PR TITLE
Add --get options for other Notification Center settings

### PR DESCRIPTION
**Pull request by gregneagle**
Also reformat help into groups of related options.

Adds:

```
  --get-show-on-lock-screen BUNDLE_ID
                        Print state of 'Show notifications on lock screen'.
  --get-badge-app-icon BUNDLE_ID
                        Print state of 'Badge app icon'.
  --get-sound BUNDLE_ID
                        Print state of 'Play sound for notifications'.
  --get-show-in-notification-center BUNDLE_ID
                        Print state of 'Show in Notification Center'.
```

### CODE REVIEW

**Comment by jacobsalmela** [comment]
It works as expected!  Thanks!!

**Comment by erikng** [comment]
It's quite crazy how different this tool is from just last week. (I figured something was up when I saw it on munki-dev).

Jacob - imagine if you used Munki and not Casper!

**Comment by jacobsalmela** [comment]
Yes, Greg has been going to town!  

I didn't realize it had reached the munki community.  That's cool!

**Comment by erikng** [comment]
I've been using it for several months (when we last spoke) but felt it was off topic for Munki. 

Greg mentioned it today in the dev group. Reading between the lines this tool is going to supplement some Munki ideas. ;)

**Comment by jacobsalmela** [comment]
Cool!  I'm glad it's useful to someone.

**Pull request merged**
