### PR TITLE
added: remove-system-center for 10.10 this will remove all apple default...

### PR DESCRIPTION
**Pull request by jasonpjohnson**
... notifications for updates and other system level updates.

added: none flag for 10.10
added: notificationcenter and usernoted killall after db commit.

refactored: set_style to allow for easier adding of specific item types and os support

### CODE REVIEW

**Comment by jacobsalmela** [comment]
You additions are pretty sweet.  I have a few questions/comments:
- in the help output you show the `-rsc` flag to remove the _ SYSTEM _ entries, but in the argument parsing, the `c` option is not there.  Did I miss something or was it just a typo?
- the `#Build Bundle Types` section condenses all my `elif`'s but do the other apps like gamecenter, reminders, or facetime just use the numbers from the `default` line?  Did these numbers change from 10.9 to 10.10?
- I think there is some indenting issues on these lines:

```
+    else:
+       c.execute("UPDATE app_info SET flags='%s' where bundleid='%s'" % (alert_style, bundle_id))
+    commit_changes()
```

**Comment by jasonpjohnson** [comment]
Thanks! 

1.) Yes help error, corrected ended with flag -s
2.) If you look at your code your default option is the same as the option for facetime, gamecenter and safari so you really can just let them fall through and let default handle them.
3.) Yes, it is really sad. - Do you have none options for 10.9 ? I do not have a 10.9 box around.
4.) Corrected - Moving between PyCharm and vim does some odd things.

image

**Comment by jacobsalmela** [comment]
What are all those XML files?

**Comment by jasonpjohnson** [comment]
Sorry - I had a commit on a computer without my global gitignore so it put a bunch of IDE setting in place. Any luck testing on 10.9 ?

**Comment by jacobsalmela** [comment]
After some testing, this seems to work as expected.  Thanks!!

**Pull request merged**
