### PR TITLE
support for osx yosemite added

### PR DESCRIPTION
**Pull request by jasonpjohnson**
This patch will add support for Yosemite! Thanks for the work on this. //Jason J

### CODE REVIEW

**Comment by jacobsalmela** [comment]
Can you please re-do your pull request and correct the spelling error in this line:

`dawrin_user_dir = os.popen('getconf DARWIN_USER_DIR').read().rstrip()`

**darwin** is spelled incorrectly.

Also, I noticed that the file path in Mavericks still exists when doing an upgrade to Yosemite.  Does 10.10 just use the new path you have in the script and ignore the settings in the user home folder?

**Comment by jasonpjohnson** [comment]
Thank you it is corrected.

We are going through a large upgrade right now and yes 10.10 will ignore the 10.9 path and data in {GUID}.db... further we tested moving a user's home directory from 10.10 to 10.10 and the notification center data does not transfer confirming that it is outside of the user's home directory.

**Comment by jacobsalmela** [comment]
Cool.  Your code works in Yosemite.

Do you know of a way to apply the changes without logging out or rebooting?  I'm not sure of what process to kill or refresh.

I have also noticed that sometimes if you remove an app, it gets restored at the next login.  Have you seen this?

**Comment by jasonpjohnson** [comment]
Apple is tricky about adding apps back, I have had a lot better luck with setting the flags to none vs removing the app completely.

After making the change run 
sudo -u {$USER} killall NotificationCenter && killall usernoted

**Pull request merged**
