### PR TITLE
Get the right NotificationCenter db when there's more than one db

### PR DESCRIPTION
**Pull request by gregneagle**
Some more changes:

Find and use the most recent NotificationCenter db when there is more than one in the directory

Move global code into functions

More minor style cleanups

### CODE REVIEW

**Comment by jacobsalmela** [comment]
It appears everything is working as expected with your changes.  I will merge the request.

As I continue to use it, I find that it would be nice to see what the existing alert style is set to.  I think that will be my next thing to do.

**Comment by gregneagle** [comment]
"As I continue to use it, I find that it would be nice to see what the existing alert style is set to." I already implemented that last night. New PR coming soon.

**Comment by jacobsalmela** [comment]
Haha.  Nice.  You are doing all my work for me!  

Thanks for all of your help.  This is awesome.

**Comment by gregneagle** [comment]
I think this will be a very useful tool for me (and others!) and am excited to contribute.

**Pull request merged**
